### ISSUE TITLE
Support of include directives

### ISSUE THREAD

**Issue by marbre** [heinzK1X/pylibconfig2#10]
The README.rst tells that "IO works via strings only. Thus, include directives are not supported.". Anyway, I found a function `read_file` in https://github.com/heinzK1X/pylibconfig2/blob/master/pylibconfig2/conf_types.py#L321. Since the README.rst is older than the `conf_types.py` this information might be deprecated.

**Comment by HeinAtCERN** [comment]
Thanks for reporting. I'll fix it.

**Comment by HeinAtCERN** [comment]
So I just changed that introductory sentence. Feel free to editing it and sending a pull-request.
