### ISSUE TITLE
lookup returns None for booleans set to False

### ISSUE THREAD

**Issue by marbre** [heinzK1X/pylibconfig2#11]
It seems that `c.lookup` fails on booleans set to `false`. I wrote a small example to demonstrate the issue.

```python
import pylibconfig2 as cfg
from pylibconfig2 import conf_types

test = """
simulation =
{
    bool_false = false
    bool_true = true
}
"""


c = cfg.Config(test)

print(c)
print('')
print(c.lookup('simulation.bool_true'))
print(c.lookup('simulation.bool_false'))
print('')
print(c.simulation.bool_true)
print(c.simulation.bool_false)
```

The out is:
```
simulation = {
  bool_false = False;
  bool_true = True;
};

True
None

True
False
```
Also `None` belongs to falsy values, I think it should be `False` instead of `None`.

**Comment by HeinAtCERN** [comment]
Thanks for the reproducer! I converted it to a test and fixed it. This is very good as all objects that evaluate to False were affected, e.g. empty strings.

Are you using py3?/Would you test my latest commit?

**Comment by marbre** [comment]
Yes, I am using python 3.3 and 3.4. I will test it tomorrow on one of my machines with pleasure. Thanks for fixing this that quickly.

**Comment by marbre** [comment]
Btw, any interest in adding a travis.yml that automatically tests python 2.7 and python3?

**Comment by HeinAtCERN** [comment]
Oh, yes. I didn't know about travis, but that's a nice tool. Would you add the file?

**Comment by marbre** [comment]
Okay, the issue is fixed for python3. Just tested it, thus closing the isse.

Regarding travis, yes I can write a `.travis.yml` and send a pull request during next week.
