### ISSUE TITLE
lookup() works incorrect with list indexes

### ISSUE THREAD

**Issue by MasterAler** [heinzK1X/pylibconfig2#3]
_ListType seems to be derived from list, but list indexes definitely start with 0, it could work some other way with the original libconfig library

Try your own example with zero index for array:
    `>> c = cfg.Config("my_array = [1, 2, 3];")`
    `>> c.lookup('my_array.[0]')`

For current right-now usage I just fixed the _lookup as follows:
    `def _lookup(self, keys):`
        `k = self.array_index.parseString(keys.pop(0))[0]`
        **if k < len(self):**

But you could recalculate indexes, so that they would start with 1, but work correct still

**Comment by heinzK1X** [comment]
I replied to this in issue #4. Please have a look.
