### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by marbre** [heinzK1X/pylibconfig2#8]
I just installed pylibconfig2 and ran the tests. For python2.7 everything is fine, but the tests fail with python3.3. Assuming the 2 in the package name determines the support python version, the question is if there are any plans to support python3 in future.

**Comment by HeinAtCERN** [comment]
No, the 2 in the name was added because pylibconfig existed already at PyPI. I don't work with python 3 myself, but others made it work with python 3 before. I really appreciate fixes, if you like to investigate and come up with one.

**Comment by marbre** [comment]
If I find some more free time, I'll dig into it. I am glad that you're willing to merge in general.

**Comment by HeinAtCERN** [comment]
Sure, no problem. If you post the bad test result, I can maybe give you a hint about what's wrong, or fix it right away.

**Comment by marbre** [comment]
Hi, since one of my students added python3 support, this issue can be closed. Thanks a lot for merging.
